import AIOImage from "@/assets/aio.png";
import assignmentBuddyImage from "@/assets/assignment-buddy.png";
import byteCanvasImage from "@/assets/bytecanvas.png";
import ReactHubImage from "@/assets/react-hub.png";
import { Project } from "../../types/projects";
import OopsipayImage from "@/assets/oopsiPay.png";
import ZanixImage from "@/assets/zanix.png";
export const projectsData: Project[] = [
  {
    id: "OopsiPAY",
    name: "OopsiPAY",
    description:
      "OopsiPAY is a secure digital wallet and payment platform built with React, TypeScript, Node.js, and MongoDB, offering seamless cash-in, cash-out, and money transfer with role-based access and analytics.",
    liveUrl: "https://oopsipay.nahid-mahmud.xyz",
    clientRepo: "https://github.com/Nahid-Mahmud/OopsiPay-Frontend",
    serverRepo: "https://github.com/Nahid-Mahmud/OopsiPay-Backend",
    tags: [
      "React",
      "TypeScript",
      "Vite",
      "Node.js",
      "Express",
      "MongoDB",
      "Redis",
      "Tailwind CSS",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
      "react-hook-form",
      "lucide-react",
      "sonner",
      "Cloudinary",
      "JWT",
      "Passport.js",
      "Mongoose",
      "SMTP",
    ],
    category: "fullstack",
    image: OopsipayImage,
    projectData: "oopsiPay.md",
    explanationVideo: "https://www.youtube.com/watch?v=SOmPx96cNWY",
  },
  {
    id: "zanix-lms",
    name: "Zanix LMS",
    description:
      "Zanix LMS is a robust, full-stack Learning Management System (LMS) designed to deliver a seamless online education experience with multiple user roles, course management, video content, and analytics.",
    image: ZanixImage,
    liveUrl: "https://zanix.nahid-mahmud.xyz/",
    clientRepo: "https://github.com/Nahid-Mahmud/Znanix-LMS-Frontend",
    serverRepo: "https://github.com/Nahid-Mahmud/Znanix-LMS-Backend.git",

    tags: [
      "Next.js",
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "Redis",
      "Tailwind CSS",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
      "Cloudinary",
      "JWT",
      "BullMQ",
      "PDFKit",
    ],
    category: "fullstack",
    projectData: "zanix-lms-project-details.markdown",
    explanationVideo: "https://www.youtube.com/watch?v=xCKLvj9XADI",
  },
  {
    id: "AIO-Chat",
    name: "AIO Chat",
    description:
      "A full-featured AI chatbot app built with Next.js and React — supporting multiple AI models, context management, and responsive UI.",
    liveUrl: "http://aio.chat.nahid-mahmud.xyz",
    clientRepo: "https://github.com/Nahid-Mahmud/personal-ai-chatbot",
    tags: ["Next.js", "React", "Redux", "Next-Themes", "Tailwind Css"],
    category: "frontend",
    image: AIOImage,
    projectData: "aioChat.md",
    explanationVideo: "https://www.youtube.com/watch?v=266ybnAr1q4",
  },

  {
    id: "reacthub",
    name: "ReactHub",
    description: "A comprehensive platform for React developers to share resources and collaborate on projects.",
    image: ReactHubImage,
    liveUrl: "https://react-hub-nahid.surge.sh/",
    clientRepo: "https://github.com/Nahid-Mahmud/react-hub-client",
    serverRepo: "https://github.com/Nahid-Mahmud/react-hub-server",
    tags: ["React", "Node.js", "MongoDB", "Express"],
    category: "fullstack",
    projectData: "reactHub.md",
  },
  {
    id: "bytecanvas",
    name: "ByteCanvas",
    description: "A digital canvas application that allows users to create and share Products online.",
    image: byteCanvasImage,
    liveUrl: "https://bytecanvas.surge.sh/",
    clientRepo: "https://github.com/Nahid-Mahmud/Byte-canvas-client",
    serverRepo: "https://github.com/Nahid-Mahmud/ByteCanvas-server",
    tags: ["React", "Firebase", "Node.js", "Express"],
    category: "fullstack",
    projectData: "byteCanvas.md",
  },
  {
    id: "assignmentbuddy",
    name: "Assignment Buddy",
    description: "An educational platform that helps students manage and collaborate on assignments.",
    image: assignmentBuddyImage,
    liveUrl: "https://assignment-buddy.surge.sh/",
    clientRepo: "https://github.com/Nahid-Mahmud/assignmnet-buddy-client",
    serverRepo: "https://github.com/Nahid-Mahmud/assignmnet-buddy-server",
    tags: ["React", "MongoDB", "Express", "JWT"],
    category: "fullstack",
    projectData: "assignmentBuddy.md",
  },
];
